---
abstract: 'Perl interface to the CyberSource Simple Order SOAP API'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Data::Dumper: 0
  English: 0
  Env: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CyberSource
no_index:
  file:
    - perlcritic.rc
  namespace:
    - Business::CyberSource::Request::Role
    - Business::CyberSource::Response::Role
    - Business::CyberSource::Role
requires:
  Business::CreditCard: 0
  Carp: 0
  Config: 0
  File::ShareDir: 0
  LWP::Protocol::https: 0
  Locale::Country: 0
  Moose: 0
  Moose::Role: 0
  MooseX::AbstractFactory: 0
  MooseX::Aliases: 0
  MooseX::SetOnce: 0.200001
  MooseX::StrictConstructor: 0
  MooseX::Traits: 0
  MooseX::Types: 0
  MooseX::Types::Common::Numeric: 0.001003
  MooseX::Types::Common::String: 0
  MooseX::Types::CreditCard: 0.001001
  MooseX::Types::DateTime::W3C: 0
  MooseX::Types::Email: 0
  MooseX::Types::Locale::Country: 0
  MooseX::Types::Locale::Currency: 0
  MooseX::Types::Moose: 0
  MooseX::Types::NetAddr::IP: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Structured: 0
  MooseX::Types::URI: 0
  MooseX::Types::Varchar: 0
  Path::Class: 0
  XML::Compile::SOAP11: 0
  XML::Compile::SOAP::WSS: 0.12
  XML::Compile::Transport::SOAPHTTP: 0
  XML::Compile::WSDL11: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/Business-CyberSource/issues
  homepage: http://search.cpan.org/dist/Business-CyberSource/
  repository: git://github.com/xenoterracide/Business-CyberSource.git
version: v0.4.1
