---
abstract: Business::CyberSource
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  Env: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200015, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CyberSource
no_index:
  file:
    - perlcritic.rc
requires:
  Carp: 0
  Config: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Traits: 0
  MooseX::Types::DateTime::W3C: 0
  MooseX::Types::Email: 0
  MooseX::Types::Locale::Country: 0
  MooseX::Types::URI: 0
  SOAP::Data::Builder: 0
  SOAP::Lite: 0
  namespace::autoclean: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/xenoterracide/Business-CyberSource/issues
  homepage: http://search.cpan.org/dist/Business-CyberSource/
  repository: git://github.com/xenoterracide/Business-CyberSource.git
version: v0.1.1
