---
abstract: 'Perl interface to the CyberSource Simple Order SOAP API'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Business::CreditCard: '0.32'
  DateTime: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::Deep: '0'
  Test::Fatal: '0'
  Test::Method: '0'
  Test::Moose: '0'
  Test::More: '0'
  Test::Requires: '0'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-CyberSource
no_index:
  file:
    - perlcritic.rc
provides:
  Business::CyberSource:
    file: lib/Business/CyberSource.pm
    version: '0.010002'
  Business::CyberSource::Client:
    file: lib/Business/CyberSource/Client.pm
    version: '0.010002'
  Business::CyberSource::Exception:
    file: lib/Business/CyberSource/Exception.pm
    version: '0.010002'
  Business::CyberSource::Exception::AttributeIsRequiredNotToBeSet:
    file: lib/Business/CyberSource/Exception/AttributeIsRequiredNotToBeSet.pm
    version: '0.010002'
  Business::CyberSource::Exception::ItemsOrTotal:
    file: lib/Business/CyberSource/Exception/ItemsOrTotal.pm
    version: '0.010002'
  Business::CyberSource::Exception::NotACreditCard:
    file: lib/Business/CyberSource/Exception/NotACreditCard.pm
    version: '0.010002'
  Business::CyberSource::Exception::Response:
    file: lib/Business/CyberSource/Exception/Response.pm
    version: '0.010002'
  Business::CyberSource::Exception::SOAPFault:
    file: lib/Business/CyberSource/Exception/SOAPFault.pm
    version: '0.010002'
  Business::CyberSource::Exception::UnableToDetectCardTypeCode:
    file: lib/Business/CyberSource/Exception/UnableToDetectCardTypeCode.pm
    version: '0.010002'
  Business::CyberSource::Factory::Request:
    file: lib/Business/CyberSource/Factory/Request.pm
    version: '0.010002'
  Business::CyberSource::Factory::Response:
    file: lib/Business/CyberSource/Factory/Response.pm
    version: '0.010002'
  Business::CyberSource::Factory::Rule:
    file: lib/Business/CyberSource/Factory/Rule.pm
    version: '0.010002'
  Business::CyberSource::Message:
    file: lib/Business/CyberSource/Message.pm
    version: '0.010002'
  Business::CyberSource::MessagePart:
    file: lib/Business/CyberSource/MessagePart.pm
    version: '0.010002'
  Business::CyberSource::Request:
    file: lib/Business/CyberSource/Request.pm
    version: '0.010002'
  Business::CyberSource::Request::AuthReversal:
    file: lib/Business/CyberSource/Request/AuthReversal.pm
    version: '0.010002'
  Business::CyberSource::Request::Authorization:
    file: lib/Business/CyberSource/Request/Authorization.pm
    version: '0.010002'
  Business::CyberSource::Request::Capture:
    file: lib/Business/CyberSource/Request/Capture.pm
    version: '0.010002'
  Business::CyberSource::Request::Credit:
    file: lib/Business/CyberSource/Request/Credit.pm
    version: '0.010002'
  Business::CyberSource::Request::DCC:
    file: lib/Business/CyberSource/Request/DCC.pm
    version: '0.010002'
  Business::CyberSource::Request::FollowOnCredit:
    file: lib/Business/CyberSource/Request/FollowOnCredit.pm
    version: '0.010002'
  Business::CyberSource::Request::Role::BillingInfo:
    file: lib/Business/CyberSource/Request/Role/BillingInfo.pm
    version: '0.010002'
  Business::CyberSource::Request::Role::CreditCardInfo:
    file: lib/Business/CyberSource/Request/Role/CreditCardInfo.pm
    version: '0.010002'
  Business::CyberSource::Request::Role::DCC:
    file: lib/Business/CyberSource/Request/Role/DCC.pm
    version: '0.010002'
  Business::CyberSource::Request::Role::TaxService:
    file: lib/Business/CyberSource/Request/Role/TaxService.pm
    version: '0.010002'
  Business::CyberSource::Request::Sale:
    file: lib/Business/CyberSource/Request/Sale.pm
    version: '0.010002'
  Business::CyberSource::Request::StandAloneCredit:
    file: lib/Business/CyberSource/Request/StandAloneCredit.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::BillTo:
    file: lib/Business/CyberSource/RequestPart/BillTo.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::BusinessRules:
    file: lib/Business/CyberSource/RequestPart/BusinessRules.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Card:
    file: lib/Business/CyberSource/RequestPart/Card.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Item:
    file: lib/Business/CyberSource/RequestPart/Item.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::PurchaseTotals:
    file: lib/Business/CyberSource/RequestPart/PurchaseTotals.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Service:
    file: lib/Business/CyberSource/RequestPart/Service.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Service::AuthReversal:
    file: lib/Business/CyberSource/RequestPart/Service/AuthReversal.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Service::Capture:
    file: lib/Business/CyberSource/RequestPart/Service/Capture.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Service::Credit:
    file: lib/Business/CyberSource/RequestPart/Service/Credit.pm
    version: '0.010002'
  Business::CyberSource::RequestPart::Service::Tax:
    file: lib/Business/CyberSource/RequestPart/Service/Tax.pm
    version: '0.010002'
  Business::CyberSource::Response:
    file: lib/Business/CyberSource/Response.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::Amount:
    file: lib/Business/CyberSource/Response/Role/Amount.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::AuthCode:
    file: lib/Business/CyberSource/Response/Role/AuthCode.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::Base:
    file: lib/Business/CyberSource/Response/Role/Base.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::DCC:
    file: lib/Business/CyberSource/Response/Role/DCC.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::ElectronicVerification:
    file: lib/Business/CyberSource/Response/Role/ElectronicVerification.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::ProcessorResponse:
    file: lib/Business/CyberSource/Response/Role/ProcessorResponse.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::ReasonCode:
    file: lib/Business/CyberSource/Response/Role/ReasonCode.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::ReconciliationID:
    file: lib/Business/CyberSource/Response/Role/ReconciliationID.pm
    version: '0.010002'
  Business::CyberSource::Response::Role::RequestDateTime:
    file: lib/Business/CyberSource/Response/Role/RequestDateTime.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::AuthReply:
    file: lib/Business/CyberSource/ResponsePart/AuthReply.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::DCCReply:
    file: lib/Business/CyberSource/ResponsePart/DCCReply.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::PurchaseTotals:
    file: lib/Business/CyberSource/ResponsePart/PurchaseTotals.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::Reply:
    file: lib/Business/CyberSource/ResponsePart/Reply.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::TaxReply:
    file: lib/Business/CyberSource/ResponsePart/TaxReply.pm
    version: '0.010002'
  Business::CyberSource::ResponsePart::TaxReply::Item:
    file: lib/Business/CyberSource/ResponsePart/TaxReply/Item.pm
    version: '0.010002'
  Business::CyberSource::Role::Currency:
    file: lib/Business/CyberSource/Role/Currency.pm
    version: '0.010002'
  Business::CyberSource::Role::ForeignCurrency:
    file: lib/Business/CyberSource/Role/ForeignCurrency.pm
    version: '0.010002'
  Business::CyberSource::Role::MerchantReferenceCode:
    file: lib/Business/CyberSource/Role/MerchantReferenceCode.pm
    version: '0.010002'
  Business::CyberSource::Role::Traceable:
    file: lib/Business/CyberSource/Role/Traceable.pm
    version: '0.010002'
  Business::CyberSource::Rule:
    file: lib/Business/CyberSource/Rule.pm
    version: '0.010002'
  Business::CyberSource::Rule::ExpiredCard:
    file: lib/Business/CyberSource/Rule/ExpiredCard.pm
    version: '0.010002'
  Business::CyberSource::Rule::RequestIDisZero:
    file: lib/Business/CyberSource/Rule/RequestIDisZero.pm
    version: '0.010002'
  MooseX::Types::CyberSource:
    file: lib/MooseX/Types/CyberSource.pm
    version: '0.010002'
requires:
  Business::CreditCard: '0.32'
  DateTime::Format::W3CDTF: '0.06'
  File::ShareDir::ProjectDistDir: '0'
  LWP::Protocol::https: '0'
  Module::Load: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Exception: '0'
  Moose::Exception::AttributeIsRequired: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::AbstractFactory: '0'
  MooseX::Aliases: '0'
  MooseX::RemoteHelper: '0'
  MooseX::RemoteHelper::CompositeSerialization: '0'
  MooseX::RemoteHelper::Types: '0'
  MooseX::SetOnce: '0.200001'
  MooseX::Types: '0'
  MooseX::Types::Common::Numeric: '0.001003'
  MooseX::Types::Common::String: '0.001005'
  MooseX::Types::CreditCard: '0.002'
  MooseX::Types::DateTime: '0'
  MooseX::Types::DateTime::W3C: '0'
  MooseX::Types::Email: '0'
  MooseX::Types::Locale::Country: '0'
  MooseX::Types::Locale::Currency: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::NetAddr::IP: '0'
  MooseY::RemoteHelper::MessagePart: '0'
  MooseY::RemoteHelper::Role::Client: '0'
  Type::Params: '0'
  Type::Utils: '0'
  Types::Standard: '0'
  XML::Compile::SOAP11: '0'
  XML::Compile::SOAP::WSS: '1.04'
  XML::Compile::Transport::SOAPHTTP: '0'
  XML::Compile::WSDL11: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/xenoterracide/business-cybersource/issues
  homepage: https://metacpan.org/release/Business-CyberSource
  repository: git://github.com/xenoterracide/business-cybersource.git
version: '0.010002'
x_contributors:
  - 'Carl Carstenson <ccarstenson@hostgator.com>'
  - 'Robert Stone <robertstone@hostgator.com>'
