
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Num
Str
datetime
merchantID
ip
cid
CVN
cvc
cvv
login
SOAPI
Bleue
Carta
Carte
Dankort
JAL
Santander
UATP
YYYY
timestamp
Overmeer
AVS
MerchantReferenceCode
env
WSDL
XSD
subclasses
auth
dcc
GüdTech
HostGator
Caleb
Cushing
xenoterracide
Carl
Carstenson
ccarstenson
lib
Business
CyberSource
MessagePart
Response
Role
AuthCode
ProcessorResponse
RequestPart
Item
Currency
Request
StandAloneCredit
Factory
BillTo
ResponsePart
PurchaseTotals
Authorization
DCC
Sale
Credit
Client
ReasonCode
TaxService
MooseX
Types
Service
AuthReversal
DCCReply
Rule
ExpiredCard
CreditCardInfo
Amount
Capture
RequestDateTime
AuthReply
BusinessRules
Reply
Card
TaxReply
BillingInfo
Tax
ForeignCurrency
RequestIDisZero
ReconciliationID
Message
FollowOnCredit
