use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Num
Str
datetime
merchantID
ip
cid
CVN
cvc
cvv
login
SOAPI
Bleue
Carta
Carte
Dankort
JAL
Santander
UATP
YYYY
timestamp
Overmeer
AVS
MerchantReferenceCode
env
WSDL
XSD
subclasses
auth
dcc
GüdTech
HostGator
Caleb
Cushing
xenoterracide
Carl
Carstenson
ccarstenson
Robert
Stone
robertstone
lib
Business
CyberSource
ResponsePart
PurchaseTotals
Response
Role
DCC
RequestDateTime
MooseX
Types
Currency
Request
Credit
Factory
Rule
RequestPart
Service
ElectronicVerification
ReasonCode
Capture
AuthReversal
Message
TaxService
RequestIDisZero
FollowOnCredit
Exception
ForeignCurrency
ReconciliationID
NotACreditCard
ExpiredCard
Tax
BillingInfo
MessagePart
Base
BillTo
AttributeIsRequiredNotToBeSet
Card
Item
ItemsOrTotal
Amount
StandAloneCredit
Traceable
Authorization
UnableToDetectCardTypeCode
AuthCode
Reply
ProcessorResponse
Sale
TaxReply
CreditCardInfo
AuthReply
Client
DCCReply
BusinessRules
SOAPFault
